# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54800b29c98b3a0d8fc3a87a8959e2d1205e890f43f8ded1ca55be39ba7a9d95af016d578d5b0db72ef60c1f5ef307e35d5796bae5c75a068ccea4706235441

test:
  secret_key_base: 4abd4fb6f9f93eb7bf76b944518adb3ee5af0f709ff3584f057b6755ac93f2823ba5a7a5ccb1e58bf0668a3a126696f31bdd5f1a271bfee39f012b231ead8a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
